#include<iostream>
#include<conio.h>
using namespace std;
int divison (int num, int den)
{
	if (den == 0)
	{
		throw runtime_error("Runtime error has occured");
	
	}
	else
	{
		return(num / den);
	}
	
}
void main()
{
	int n = 10;
	int d = 0;
	int result;
	
	try
	{
		result = divison(n, d);
		cout << "The quotient is" << result << endl;

	}
	catch (runtime_error & e)
	{
		cout << "404 not found" << endl << e.what();
	}
	_getch();
}
